apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Install Istio Control Plane and Data Planes.
  # The Control Plane needs to be installed first, and then the rest of the
  # components. This is managed by ArgoCD wave control.
  - istio-control-plane.yaml
  - istio-external-gateways.yaml
  - istio-multicluster-gateways.yaml
