env: staging

# === Application Onboarding with ArgoCD ==================================== #
#
#   ArgoCD template setup is going to loop through the items in slice here,
#   and search for `name` inside `get-gitops-k8s/stack/`. If the `enabled`
#   boolean flag is set to `false`, ArgoCD will ignore.
#
#   Additionally, you can specify `namespace`. This may be useful when the
#   installation requires a specific namespace in place.
#
#   If `stack` does not comply with the directory format ArgoCD expects,
#   ArgoCD sync will be halted until it is fixed.
#
apps:
  - name: istio
    enabled: true
    namespace: istio-system
  - name: istio-setup
    enabled: true
    path: ../istio-setup/ # Relative from `clusters/armadillo/argocd/`
#
# =========================================================================== #

# === ArgoCD Setup ========================================================== #
#
# Metadata
metadata:
  finalizers:
    enabled: true
# Overrides
spec:
  source:
    gitRepoUrl: https://github.com/rytswd/get-istio-multicluster
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune:
        # Specifies if resources should be pruned during auto-syncing
        # ( false by default ).
        enabled: true
      selfHeal:
        # Specifies if partial app sync should be executed when resources
        # are changed only in target Kubernetes cluster and no git change
        # detected ( false by default ).
        enabled: true
#
# =========================================================================== #
