apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: armadillo-offerings

resources:
  - color-svc-account.yaml
  - color-svc-only-blue.yaml
  - httpbin.yaml
  - toolkit-alpine.yaml
