apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: armadillo-istio-external-gateways
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # Profile empty is used to create Gateways only.
  profile: empty

  components:
    egressGateways:
      - enabled: true
        name: armadillo-external-egressgateway
        label:
          app: armadillo-external-egressgateway

    ingressGateways:
      - enabled: true
        name: armadillo-external-ingressgateway
        label:
          app: armadillo-external-ingressgateway
        k8s:
          # In case of LB usage in real environment, you may want to create
          # IP from the cloud provider service, and use it here.
          # service:
          #   loadBalancerIP: TBC

          # Affinity for IngressGateways, so that pods are separated into
          # different nodes.
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: armadillo-external-ingressgateway
                  topologyKey: kubernetes.io/hostname
          # HPA setup, which is commented out for local testing.
          # hpaSpec:
          #   maxReplicas: 5
          #   metrics:
          #     - resource:
          #         name: cpu
          #         targetAverageUtilization: 80
          #       type: Resource
          #   minReplicas: 3
          #   scaleTargetRef:
          #     apiVersion: apps/v1
          #     kind: Deployment
          #     name: armadillo-external-ingressgateway
