apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: armadillo-istio-control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # The minimal profile is a good base with control plane setup.
  profile: minimal

  # TODO: Remove addon components, as these are deprecated
  # Addon components include Grafana, Jaeger and other useful set. For this
  # setup, we only get the essential setup, which is istiocoredns.
  addonComponents:
    istiocoredns:
      enabled: true

  components:
    # For Istiod setup
    pilot:
      k8s:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: istiod
                topologyKey: kubernetes.io/hostname

        # Reduce resource requirements for local testing. This is NOT
        # recommended for the real use cases.
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi

        # HPA setup, which is commented out for local testing.
        # hpaSpec:
        #   maxReplicas: 5
        #   metrics:
        #     - resource:
        #         name: cpu
        #         targetAverageUtilization: 80
        #       type: Resource
        #   minReplicas: 3
        #   scaleTargetRef:
        #     apiVersion: apps/v1
        #     kind: Deployment
        #     name: istiod

  meshConfig:
    accessLogFile: /dev/stdout

  values:
    global:
      # pilotCertProvider: kubernetes
      controlPlaneSecurityEnabled: true
      multiCluster:
        # clusterName: armadillo
        enabled: true # Only used for istio-sidecar-injector ConfigMap
      podDNSSearchNamespaces:
        - global
