---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: armadillo-color-svc-routing
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/armadillo-external-ingressgateway
  http:
    - match:
        - uri:
            prefix: /chaos
      rewrite:
        uri: /random
      route:
        - destination:
            host: color-svc-only-blue.armadillo-offerings.svc.cluster.local
            port:
              number: 8800
      fault:
        abort:
          percentage:
            value: 50
          httpStatus: 400
