apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: bison-istio-multicluster-gateways
spec:
  # Profile empty is used to create Gateways only.
  profile: empty

  components:
    egressGateways:
      - enabled: true
        name: bison-multicluster-egressgateway
        label:
          app: bison-multicluster-egressgateway
        # k8s:
        #   env:
        #     - name: ISTIO_META_REQUESTED_NETWORK_VIEW
        #       value: external

    ingressGateways:
      - enabled: true
        name: bison-multicluster-ingressgateway
        label:
          app: bison-multicluster-ingressgateway
        k8s:
          service:
            # In case of LB usage in real environment, you may want to create
            # IP from the cloud provider service, and use it here.
            # loadBalancerIP: TBC
            ports:
              - port: 80
                targetPort: 8080
                name: http2
              - port: 443
                targetPort: 8443
                name: https
              - port: 15443
                targetPort: 15443
                name: tls
                nodePort: 32001 # This is for KinD based testing. Make sure this doesn't clash with other mesh definitions.

          # Affinity for IngressGateways, so that pods are separated into
          # different nodes.
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: bison-multicluster-ingressgateway
                  topologyKey: kubernetes.io/hostname
          # HPA setup, which is commented out for local testing.
          # hpaSpec:
          #   maxReplicas: 4
          #   metrics:
          #     - resource:
          #         name: cpu
          #         targetAverageUtilization: 80
          #       type: Resource
          #   minReplicas: 2
          #   scaleTargetRef:
          #     apiVersion: apps/v1
          #     kind: Deployment
          #     name: bison-multicluster-ingressgateway
  # values:
  #   global:
  #     meshID: simple-istio-multicluster
  #     multiCluster:
  #       clusterName: bison
  #       enabled: true # Only used for istio-sidecar-injector ConfigMap
  #     podDNSSearchNamespaces:
  #       - global
  #     # pilotCertProvider: kubernetes
  #     # controlPlaneSecurityEnabled: true
