apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: bison-istio-management-gateway
  annotations:
    # ArgoCD Wave setup for controlling the timing of sync.
    argocd.argoproj.io/sync-wave: "2"
spec:
  # Profile empty is used to create Gateways only.
  profile: empty

  components:
    ingressGateways:
      - enabled: true
        name: bison-management-ingressgateway
        label:
          app: bison-management-ingressgateway
        k8s:
          service:
            # In case of LB usage in real environment, you may want to create
            # IP from the cloud provider service, and use it here.
            # loadBalancerIP: TBC

            ports:
              - port: 80
                targetPort: 8080
                name: http2
                nodePort: 32032 # This is for KinD based testing. Make sure this doesn't clash with other mesh definitions.
              - port: 443
                targetPort: 8443
                name: https
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017

          # Affinity for IngressGateways, so that pods are separated into
          # different nodes.
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: bison-management-ingressgateway
                  topologyKey: kubernetes.io/hostname
          # HPA setup, which is commented out for local testing.
          # hpaSpec:
          #   maxReplicas: 5
          #   metrics:
          #     - resource:
          #         name: cpu
          #         targetAverageUtilization: 80
          #       type: Resource
          #   minReplicas: 3
          #   scaleTargetRef:
          #     apiVersion: apps/v1
          #     kind: Deployment
          #     name: bison-management-ingressgateway
