name: ChatOps
on:
  issue_comment:
    # This shouldn't be called for comment deletion
    types:
      - created
      - edited

jobs:
  chatops:
    name: ChatOps
    runs-on: ubuntu-latest

    steps:
      - name: Handle with Comvent
        uses: rytswd/comvent@v0.3
        if: ${{ !github.event.issue.pull_request }} # Run only if it's issue comment, not PR
        id: comvent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/chatops-config.yaml

      #* ---------------------------------------------------------------------- *#

      - if: steps.comvent.outputs.comvent-found-any-match != ''
        uses: actions/checkout@v2

      - if: steps.comvent.outputs.comvent-found-any-match != ''
        run: |
          curl -sSL https://istio.io/downloadIstio | ISTIO_VERSION=1.8.0 sh -
          echo "$HOME/istio-1.8.0/bin" >> $GITHUB_PATH

      - if: steps.comvent.outputs.comvent-found-any-match != ''
        name: Start Armadillo KinD cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.9.0
          name: armadillo
          config: ./tools/kind-config/config-2-nodes-port-32021.yaml

      - if: steps.comvent.outputs.comvent-found-any-match != ''
        name: Start Bison KinD cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.9.0
          name: bison
          config: ./tools/kind-config/config-2-nodes-port-32022.yaml

      - if: steps.comvent.outputs.comvent-found-any-match != ''
        name: Start Dolphin KinD cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.9.0
          name: dolphin
          config: ./tools/kind-config/config-2-nodes-port-32024.yaml

      - if: steps.comvent.outputs.comvent-found-any-match != ''
        name: Prep CA certs
        run: |
          ./tools/steps/step-3-prep-ca-certs.sh

      - if: steps.comvent.outputs.comvent-found-any-match != ''
        name: Install ArgoCD
        run: |
          export userToken=${{ secrets.USER_TOKEN }}
          ./tools/steps/step-4-argocd-install.sh
